// const numberButtons = document.querySelectorAll('[data-number]')
// const operationsButtons = document.querySelectorAll('[data-operation]')
// const clearButton = document.querySelector('[data-all-clear]')
// const equalsButton = document.querySelector(['data-equals'])
// const deleteButton = document.querySelector(['data-delete'])
// console.log(deleteButton)